export const background = require('@images/background.png')
export const offline = require('@images/offline.jpeg')
export const maintenance = require('@images/maintenance.png')
export const transferLoading = require('@images/transfer-loading.png')
export const hotelLoading = require('@images/hotel-loading.png')
export const activityLoading = require('@images/activity-loading.png')
export const carLoading = require('@images/car-loading.png')
export const flightLoading = require('@images/flight-loading.png')
export const logo = require('@images/logo.png')
export const white_logo = require('@images/white_logo.png')
export const homeBack = require('@images/home_back.png')
export const mapPin = require('@images/map-pin.png')
export const emptyAvatar = require('@images/placeholder.jpg')
export const location = require('@images/location.png')
export const hotel1 = require('@images/hotel1.png')

//tab icons

export const home_grey = require('@images/tabIcons/home_grey.png')
export const home_primary = require('@images/tabIcons/home_primary.png')
export const package_grey = require('@images/tabIcons/package_grey.png')
export const package_primary = require('@images/tabIcons/package_primary.png')
export const hotdeal_grey = require('@images/tabIcons/hotdeal_grey.png')
export const hotdeal_primary = require('@images/tabIcons/hotdeal_primary.png')
export const mycart_grey = require('@images/tabIcons/mycart_grey.png')
export const mycart_primary = require('@images/tabIcons/mycart_primary.png')
export const profile_grey = require('@images/tabIcons/profile_grey.png')
export const profile_primary = require('@images/tabIcons/profile_primary.png')


// other icons
export const sortIcon = require('@images/icons/sortIcon.png')
export const filterIcon = require('@images/icons/filterIcon.png')
export const mapIcon = require('@images/icons/mapIcon.png')
export const bedIcon = require('@images/icons/bed.png')
export const nightIcon = require('@images/icons/night.png')
export const calendarIcon = require('@images/icons/calendar.png')
export const navigationIcon = require('@images/icons/navigation.png')
export const chatIcon = require('@images/icons/chatIcon.png')
export const infoIcon = require('@images/icons/infoIcon.png')
export const removeIcon = require('@images/icons/removeIcon.png')


export const messageBlack = require('@images/icons/message_black.png')
export const messageWhite = require('@images/icons/message_white.png')
export const messageGreen = require('@images/icons/message_green.png')
export const mobileBlack = require('@images/icons/mobile_black.png')
export const mobileWhite = require('@images/icons/mobile_white.png')
export const mobileGreen = require('@images/icons/mobile_green.png')
export const locked = require('@images/icons/locked.png')
export const closeButtonImage = require('@images/icons/ios7-close-empty.png')
export const roomImage = require('@images/room.png')
export const facilityIcon1 = require('@images/facility1.png')
export const avatar = require('@images/avatar.png')